name: Build site
run-name: ${{ github.actor }} run build site
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - run: tmux kill-session -t front || echo "No front session"
      - run: tmux kill-session -t back || echo "No back session"
      - run: ls -la
      - run: pip3 install -r backend/requirements/base.txt
      - run: pip3 install -r backend/requirements/tests.txt

