name: Build site
run-name: ${{ github.actor }} run build site
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build compose
        run: cd backend && docker-compose up --build -d
      - name: Run tests
        run: cd backend && docker-compose run fastapi_template pytest .
  Build:
    runs-on: self-hosted
    steps:
      - run: tmux kill-session -t front || echo "No front session"
      - run: tmux kill-session -t back || echo "No back session"
      - run: pip3 install -r backend/requirements/base.txt
      - run: pip3 install -r backend/requirements/tests.txt

